name: SkinGuard
version: 1.0.0
main: vape\skinguard\SkinGuard
api: 5.0.0
author: vape (@vapebw, @sxvape)
load: POSTWORLD
permissions:
  skinguard.bypass:
    description: "Bypass skin size and geometry limits"
    default: op
  skinguard.admin:
    description: "Access to /skinguard command"
    default: op

commands:
  skinguard:
    description: "Check skin status or reload plugin"
    permission: skinguard.admin
    aliases: ["sg"]
